version: "3.8"
services:
  app:
    container_name: 'app'
    build: './'
    volumes:
      - "./:/app"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"