// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: messages/user_registered.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserRegistered with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserRegistered) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserRegistered with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserRegisteredMultiError,
// or nil if none found.
func (m *UserRegistered) ValidateAll() error {
	return m.validate(true)
}

func (m *UserRegistered) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserId() < 0 {
		err := UserRegisteredValidationError{
			field:  "UserId",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetEmail()) < 1 {
		err := UserRegisteredValidationError{
			field:  "Email",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UserRegisteredMultiError(errors)
	}
	return nil
}

// UserRegisteredMultiError is an error wrapping multiple validation errors
// returned by UserRegistered.ValidateAll() if the designated constraints
// aren't met.
type UserRegisteredMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserRegisteredMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserRegisteredMultiError) AllErrors() []error { return m }

// UserRegisteredValidationError is the validation error returned by
// UserRegistered.Validate if the designated constraints aren't met.
type UserRegisteredValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserRegisteredValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserRegisteredValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserRegisteredValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserRegisteredValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserRegisteredValidationError) ErrorName() string { return "UserRegisteredValidationError" }

// Error satisfies the builtin error interface
func (e UserRegisteredValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserRegistered.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserRegisteredValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserRegisteredValidationError{}
